remove `new_process` allocation hacks
These have existed ever since the initial version of MS-DOS Player,
presumably to patch over emulation inaccuracies that have since been
fixed. Right now, they enforce that any new process is placed into the
last memory block even if there's enough free memory elsewhere,
bypassing the intended allocation strategy.
These hacks break Turbo C++ 4.0's invocations of `TLINK.EXE` when using
`TCC.EXE` as a compiler+linker. The rough sequence of allocations looks
like this:

1. tcc.exe launches rtm.exe
2. rtm claims all remaining conventional memory on startup
3. rtm resizes itself to a much smaller size, leaving a large hole in
   conventional RAM
4. rtm allocates a small bit of memory at the top of conventional RAM
5. tcc launches tlink.exe, which is supposed to be placed into the hole
   left by 3), but `new_process == true` forces it to be placed in the
   space that is now occupied by 4)

A minimal reproducible example:

• Create `nop.c` with the following contents:

  int main(void) { return 0; }

• Run `msdos -e -x tcc -mt -lt nop.c`. Without this fix:

    $ .\msdos -e -x tcc -mt -lt nop.c
    Turbo C++ Version 4.02 Copyright (c) 1994 Borland International
    nop.c:
    Error: Unable to execute command 'tlink.exe'

  With this fix, the code is compiled and linked into `NOP.COM`, as
  expected:

    $ .\msdos -e -x tcc -mt -lt nop.c
    Turbo C++ Version 4.02 Copyright (c) 1994 Borland International
    nop.c: